name: Backup and Reset Codebase For Sharepoint

on:
  workflow_dispatch:
    inputs:
      backup_branch_name:
        description: 'Name of the backup branch (optional)'
        required: false
        type: string

permissions:
  issues: write
  contents: write

env:
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_PRIVATE_KEY_BASE64: ${{ secrets.AZURE_PRIVATE_KEY_BASE64 }}
  AZURE_PFX_PASSWORD: ${{ secrets.AZURE_PFX_PASSWORD }}
  AZURE_THUMBPRINT: ${{ secrets.AZURE_THUMBPRINT }}

jobs:
  backup-and-reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create backup branch
        id: backup
        run: |
          # Get current date and time in YYYY-MM-DD-HH-MM format
          TIMESTAMP=$(date +%Y-%m-%d-%H-%M)
          # Use provided branch name or default to backup-{timestamp}
          BRANCH_NAME="${INPUT_BACKUP_BRANCH_NAME:-backup-$TIMESTAMP}"
          # Create and push the backup branch
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Reset main to specified commit
        run: |
          git checkout main
          git reset --hard ${{ secrets.INITIAL_RESET_COMMIT }}
          git push origin main --force


      - name: Create setup issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Setup the repository',
              body: 'Setup the repository',
              labels: ['aemy-help', 'aemy-go', 'aemy-merge']
            });


      - name: Set up sta-sp-delete action dependencies
        run: |
          cd .github/actions/sta-sp-delete
          npm install

      - name: Set up sta-sp-move-to-backup action dependencies
        run: |
          cd .github/actions/sta-sp-move-to-backup
          npm install

      - name: Set up sta-azure-helper action dependencies
        run: |
          cd .github/actions/sta-azure-helper
          npm install

      - name: Set up sta-mountpoint action dependencies
        run: |
          cd .github/actions/sta-mountpoint
          npm install

      - name: Create Azure Access Token
        uses: ./.github/actions/sta-azure-helper
        id: azure-auth
        with:
          tenant_id: ${{ env.AZURE_TENANT_ID }}
          client_id: ${{ env.AZURE_CLIENT_ID }}
          key: ${{ env.AZURE_PRIVATE_KEY_BASE64 }}
          password: ${{ env.AZURE_PFX_PASSWORD }}
          thumbprint: ${{ env.AZURE_THUMBPRINT }}
          duration: 3600

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Extract root_mountpoint from fstab.yaml
        id: extract_mountpoint
        run: |
          root_mountpoint=$(yq '.mountpoints["/"]' fstab.yaml | sed 's/^"//;s/"$//')
          echo "root_mountpoint=$root_mountpoint" >> $GITHUB_OUTPUT

      - name: Parse mountpoint
        id: mountpoint_data
        uses: ./.github/actions/sta-mountpoint
        with:
          mountpoint: ${{ steps.extract_mountpoint.outputs.root_mountpoint }}
          mountpoint_type: 'sharepoint'

      - name: Move SharePoint content to backup folder
        id: move-to-backup
        uses: ./.github/actions/sta-sp-move-to-backup
        with:
          token: ${{ steps.azure-auth.outputs.access_token }}
          sp_host: ${{ fromJSON(steps.mountpoint_data.outputs.data).host }}
          sp_site_path: ${{ fromJSON(steps.mountpoint_data.outputs.data).site }}
          sp_folder_path: ${{ fromJSON(steps.mountpoint_data.outputs.data).path }}

      - name: Delete SharePoint previews
        id: delete-previews
        uses: ./.github/actions/sta-sp-delete
        with:
          context: |
            {"project": {"owner": "${{ github.repository_owner }}", "repo": "${{ github.event.repository.name }}", "branch": "main"}}
          urls: ${{ steps.filter_urls.outputs.urls }}

      - name: Filter URLs for deletion
        id: filter_urls
        run: |
          urls=$(jq -r '.urls[] | select(.status != "EXCLUDED") | .url' tools/importer/site-urls.json | paste -sd, -)
          echo "urls=$urls" >> $GITHUB_OUTPUT
